using System;
using System.IO;
using Microsoft.VisualBasic.FileIO;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Please enter a .csv file name");

            string? fileName = Console.ReadLine();
            
            while (fileName == null || !File.Exists(fileName))
            {
                Console.WriteLine("File does not exist");
                fileName = Console.ReadLine();
            }

            Dictionary<string, Dictionary<string, int>> mainDictionary = ReadCsvFile(fileName);

            applyLaplacianSmoothing(mainDictionary);
            printDictionary(mainDictionary);
        }

        private static void printDictionary(Dictionary<string, Dictionary<string, int>> mainDictionary)
        {
            foreach (var keyValuePair in mainDictionary)
            {
                Console.WriteLine("\n" + keyValuePair.Key + ":");

                foreach (var subKeyValuePair in keyValuePair.Value)
                {
                    Console.WriteLine(subKeyValuePair.Key + " " + subKeyValuePair.Value);
                }
            }
        }

        // this method applies laplacian smoothing to the dictionary
        private static void applyLaplacianSmoothing(Dictionary<string, Dictionary<string, int>> mainDictionary)
        {
            foreach (var keyValuePair in mainDictionary)
            {
                foreach (var subKeyValuePair in keyValuePair.Value.ToList())
                {
                    int value = subKeyValuePair.Value;
                    value++;
                    keyValuePair.Value[subKeyValuePair.Key] = value;
                }
            }
        }

        // this method reads a csv file and returns a dictionary
        // Generated by copilot
        private static Dictionary<string, Dictionary<string, int>> ReadCsvFile(string fileName)
        {
            // the first line of the csv file is the header
            // we will use it to create the main dictionary keys
            // and the sub dictionary keys will be the values in the csv file
            // and the sub dictionary values will be the count of the values in the csv file

            Dictionary<string, Dictionary<string, int>> mainDictionary = new Dictionary<string, Dictionary<string, int>>();

            using (TextFieldParser parser = new TextFieldParser(fileName))
            {
                parser.TextFieldType = FieldType.Delimited;
                parser.SetDelimiters(",");

                // read the header
                string[] header = parser.ReadFields();

                // create the main dictionary keys
                foreach (string headerValue in header)
                {
                    mainDictionary.Add(headerValue, new Dictionary<string, int>());
                }

                // read the rest of the csv file
                while (!parser.EndOfData)
                {
                    string[] fields = parser.ReadFields();

                    // create the sub dictionary keys
                    for (int i = 0; i < fields.Length; i++)
                    {
                        string fieldValue = fields[i];

                        // if the sub dictionary key already exists, increment the count
                        if (mainDictionary[header[i]].ContainsKey(fieldValue))
                        {
                            mainDictionary[header[i]][fieldValue]++;
                        }
                        // if the sub dictionary key does not exist, add it to the sub dictionary
                        else
                        {
                            mainDictionary[header[i]].Add(fieldValue, 1);
                        }
                    }
                }
            }

            return mainDictionary;
        }
    }
}